# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Lorem= "Accusamus drinking vinegar nulla bicycle rights, letterpress consequat culpa Banksy minim selvage next level. Cupidatat VHS vinyl, labore try-hard 8-bit aesthetic DIY whatever. Polaroid anim deep v beard. Beard chia fixie Marfa, Truffaut reprehenderit occaecat normcore brunch. Officia sed brunch, four loko vinyl nihil aliquip Etsy squid ea blog velit. Meditation slow-carb banh mi, flexitarian velit food truck single-origin coffee tote bag pickled chambray meggings migas meh bitters. Fashion axe tofu cardigan listicle quinoa stumptown."
User.destroy_all
User.create(first_name: "Jason", last_name: "haas", email: "jasonbhaas@gmail.com", password: "1234", password_confirmation: "1234", location: "Cape Town", english: "Native Speaker", french: "Not Interested", spanish: "Advanced", italian: "Not Interested", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Haley", last_name: "Bowler", email: "haley@gmail.com", password: "1234", password_confirmation: "1234", location: "Cape Town", english: "Native Speaker", french: "Not Interested", spanish: "Native Speaker", italian: "Not Interested", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Rachel", last_name: "Knapp", email: "rachel@gmail.com", password: "1234", password_confirmation: "1234", location: "Paris", english: "Native Speaker", french: "Not Interested", spanish: "Beginner", italian: "Not Interested", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Jose", last_name: "Maria", email: "Jose@gmail.com", password: "1234", password_confirmation: "1234", location: "Barcelona", english: "Native Speaker", french: "Not Interested", spanish: "Native Speaker", italian: "Beginner", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Alex", last_name: "Bailey", email: "alex@gmail.com", password: "1234", password_confirmation: "1234", location: "Berlin", english: "Native Speaker", french: "Not Interested", spanish: "Native Speaker", italian: "Not Interested", german: "Native Speaker", about_me: Lorem)
User.create(first_name: "Hans", last_name: "von Krusenstiern", email: "Hans@gmail.com", password: "1234", password_confirmation: "1234", location: "Berlin", english: "Beginner", french: "Not Interested", spanish: "Not Interested", italian: "Not Interested", german: "Native Speaker", about_me: Lorem)
User.create(first_name: "Adela", last_name: "Kantor", email: "adela@gmail.com", password: "1234", password_confirmation: "1234", location: "Berlin", english: "Intermediate", french: "Not Interested", spanish: "Beginner", italian: "Not interested", german: "Advanced", about_me: Lorem)
User.create(first_name: "Noelle", last_name: "Rosellini", email: "Noelle@gmail.com", password: "1234", password_confirmation: "1234", location: "Rome", english: "Native Speaker", french: "Advanced", spanish: "Native Speaker", italian: "Native Speaker", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Victor", last_name: "Ramirez", email: "Victor@gmail.com", password: "1234", password_confirmation: "1234", location: "Madrid", english: "Native Speaker", french: "Not Interested", spanish: "Native Speaker", italian: "Advanced", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Isabella", last_name: "Bertagna", email: "Isabella@gmail.com", password: "1234", password_confirmation: "1234", location: "Milan", english: "Native Speaker", french: "Not Interested", spanish: "Native Speaker", italian: "Beginner", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Joaquin", last_name: "Garces", email: "Joaqin@gmail.com", password: "1234", password_confirmation: "1234", location: "Madrid", english: "Native Speaker", french: "Not Interested", spanish: "Native Speaker", italian: "Beginner", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Sophia", last_name: "Gant", email: "Sophia@gmail.com", password: "1234", password_confirmation: "1234", location: "Paris", english: "Native Speaker", french: "Advanced", spanish: "Native Speaker", italian: "Beginner", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Emilia", last_name: "Luu", email: "Emilia@gmail.com", password: "1234", password_confirmation: "1234", location: "Rome", english: "Native Speaker", french: "Advanced", spanish: "Not Interested", italian: "Beginner", german: "Not Interested", about_me: Lorem)
User.create(first_name: "Sarah", last_name: "Bertrand", email: "Sarah@gmail.com", password: "1234", password_confirmation: "1234", location: "Nice", english: "Native Speaker", french: "Advanced", spanish: "Not Interested", italian: "Beginner", german: "Not Interested", about_me: Lorem)